# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:      # pipeline-level
  SERVICENAME: 'AzureDB'
  ConnectionString: 'Server=myServerAddress;Database=myDataBase;Trusted_Connection=True;'

steps:
- script: |
    echo ##vso[task.setvariable variable=InterpolatedConnectionString]$(ConnectionString)--$(SERVICENAME)
    SET variable="$(ConnectionString)--$(SERVICENAME)"
    echo %variable%
  displayName: 'Run a multi-line script'

- script: |
    echo $(InterpolatedConnectionString)
  displayName: 'Run a multi-line script'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN(93ddb8b3-ddb9-4d1c-ba59-421456e65538)'
    KeyVaultName: 'josh-keyvault'
    SecretsFilter: '*'