# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:      # pipeline-level
  SERVICENAME: 'AzureDB'
  ConnectionString: 'Server=myServerAddress;Database=myDataBase;Trusted_Connection=True;'

steps:
- script: |
    echo ##vso[task.setvariable variable=InterpolatedConnectionString]$(ConnectionString)--$(SERVICENAME)
    echo $(InterpolatedConnectionString)
    SET variable="$(ConnectionString)--$(SERVICENAME)"
    echo %variable%
    echo $ENV:InterpolatedConnectionString
    echo $(ENV:InterpolatedConnectionString)
  displayName: 'Run a multi-line script'

- script: |
    echo $(InterpolatedConnectionString)
  displayName: 'Run a multi-line script'